"""costs

Revision ID: 4fbeddeb6a6c
Revises: a1b2c3d4e5f6
Create Date: 2026-03-09 21:13:56.373599

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4fbeddeb6a6c"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cost_rate_per_hour", sa.Float(), nullable=False, server_default="0.0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("cost_rate_per_hour")

    # ### end Alembic commands ###
